apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-container-build
spec:
  #serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: gh-trigger
      interceptors:
        - github:
            secretRef:
              secretName: tekton-webhook
              secretKey: key
            eventTypes:
              - push
              - ping
      bindings:
        - ref: github-binding
      template:
        name: container-build